version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/project/TP -Techniques de test/
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort
      - run:
          name: Test
          command: mvn verify
      - codecov/upload

workflows:
  sample:
    jobs:
      - build-and-test