version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/project/TP -Techniques de test
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn verify
      - codecov/upload

workflows:
  sample:
    jobs:
      - build-and-test