version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn verify
      - codecov/upload:
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: AlexisSaccoman/ceri-m1-techniques-de-test

workflows:
  sample:
    jobs:
      - build-and-test